all:
	# gcc orderArray.c -o orderArray
	# gcc linkList.c -o linkList
	# gcc sparseMatrix.c -o sparseMatrix
	# gcc polynomial.c -o polynomial
	# gcc test.c -o test
	# gcc maze.c -o maze
	gcc stack.c -o stack
clean:
	rm -rf orderArray linkList sparseMatrix polynomial test maze stack