jall:
	# gcc orderArray.c -o orderArray
	# gcc linkList.c -o linkList
	# gcc sparseMatrix.c -o sparseMatrix
	# gcc polynomial.c -o polynomial
	# gcc test.c -o test
	# gcc maze.c -o maze
	# gcc stack.c -o stack
	# gcc circularQueue.c -o circularQueue
	gcc texteditor.c -o texteditor
clean:
	rm -rf orderArray linkList sparseMatrix polynomial test maze stack circularQueue