all:
	# gcc orderArray.c -o orderArray
	# gcc linkList.c -o linkList
	# gcc sparseMatrix.c -o sparseMatrix
	gcc polynomial.c -o polynomial
	gcc test.c -o test
clean:
	rm -rf orderArray linkList sparseMatrix polynomial test