all:
	gcc binaryTree.c -o binaryTree -lm
	gcc threadedBinaryTree.c -o threadedBinaryTree -lm
	gcc heap.c -o heap -lm
	gcc binarySearchTree.c -o binarySearchTree -lm
clean:
	rm -rf binaryTree threadedBinaryTree heap binarySearchTree