all:
	# g++ learnDeque.cpp -o learnDeque
	# g++ learnStack.cpp -o learnStack
	# g++ learnPriorityQueue.cpp -o learnPriorityQueue
	# g++ learnVector.cpp -o learnVector
	# g++ learnLinkedList.cpp -o learnLinkedList
	# g++ learnSingleLinkedList.cpp -o learnSingleLinkedList
	g++ learnSet.cpp -o learnSet

clean:
	rm -rf learnDeque learnStack learnPriorityQueue learnVector learnLinkedList learnSingleLinkedList