all:
	# g++ learnDeque.cpp -o learnDeque
	# g++ learnStack.cpp -o learnStack
	# g++ learnPriorityQueue.cpp -o learnPriorityQueue
	# g++ learnVector.cpp -o learnVector
	# g++ learnLinkedList.cpp -o learnLinkedList
	# g++ learnSingleLinkedList.cpp -o learnSingleLinkedList
	# g++ learnSet.cpp -o learnSet
	# g++ neoj36.cpp -o neoj36
	# g++ brackets.cpp -o brackets
	# g++ fourOperations.cpp -o fourOperations

clean:
	rm -rf learnDeque learnStack learnPriorityQueue learnVector learnLinkedList learnSingleLinkedList
	rm -rf learnSet neoj36 brackets twoOperations